name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Build with dotnet
      run: dotnet build Records/Records.sln -c Release
      
    - name: Run unit tests
      run: dotnet test Records/RecordsTests/RecordsTests.csproj
      
    - name: Generate nuget package
      run: dotnet pack --configuration Release -o nupkg
      working-directory: Records
