name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Build with dotnet
      run: dotnet build Records/Records.sln -c Release
      
    - name: Run unit tests
      run: dotnet test Records/RecordsTests/RecordsTests.csproj
            --no-build

    - name: Push package to nuget
      run: dotnet nuget push **/*.nupkg
            --api-key ${{ secrets. NUGET_API_KEY }}
            --source https://api.nuget.org/v3/index.json
